"""Initial migration with full schema

Revision ID: 0affe9a8d3b4
Revises: 
Create Date: 2026-04-27 17:08:46.761548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0affe9a8d3b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('promo', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_date'), 'exams', ['date'], unique=False)
    op.create_index(op.f('ix_exams_promo'), 'exams', ['promo'], unique=False)
    op.create_table('proctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prof_capacity', sa.Integer(), nullable=False),
    sa.Column('resident_capacity', sa.Integer(), nullable=False),
    sa.Column('proctor_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PROCTOR', 'SUPER_ADMIN', name='user_role'), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('staff_type', sa.Enum('prof', 'resident', name='staff_type'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'room_id', name='uq_assignment_exam_room')
    )
    op.create_index(op.f('ix_assignments_exam_id'), 'assignments', ['exam_id'], unique=False)
    op.create_index(op.f('ix_assignments_room_id'), 'assignments', ['room_id'], unique=False)
    op.create_table('config_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.Enum('PROFESSOR', 'RESIDENT', 'ROOM', 'PROCTOR', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='actiontype'), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_change_logs_action'), 'config_change_logs', ['action'], unique=False)
    op.create_index(op.f('ix_config_change_logs_entity_id'), 'config_change_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_config_change_logs_entity_type'), 'config_change_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_config_change_logs_id'), 'config_change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_config_change_logs_timestamp'), 'config_change_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_config_change_logs_user_id'), 'config_change_logs', ['user_id'], unique=False)
    op.create_table('exam_room',
    sa.Column('exam_id', sa.String(length=36), nullable=True),
    sa.Column('room_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], )
    )
    op.create_table('history_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date_saved', sa.DateTime(), nullable=True),
    sa.Column('period_name', sa.String(), nullable=True),
    sa.Column('exams_snapshot', sa.JSON(), nullable=True),
    sa.Column('assignments_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_records_id'), 'history_records', ['id'], unique=False)
    op.create_index(op.f('ix_history_records_period_name'), 'history_records', ['period_name'], unique=False)
    op.create_index(op.f('ix_history_records_user_id'), 'history_records', ['user_id'], unique=False)
    op.create_table('professors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rank', sa.Enum('Pr', 'Dr', name='prof_rank'), nullable=False),
    sa.Column('responsible_promo', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professors_name'), 'professors', ['name'], unique=False)
    op.create_table('residents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residents_name'), 'residents', ['name'], unique=False)
    op.create_table('room_proctor',
    sa.Column('proctor_id', sa.String(length=36), nullable=True),
    sa.Column('room_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['proctor_id'], ['proctors.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], )
    )
    op.create_table('absences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('professor_id', sa.String(length=36), nullable=True),
    sa.Column('resident_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(professor_id IS NOT NULL) OR (resident_id IS NOT NULL)', name='absence_has_entity'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctor_assignment',
    sa.Column('proctor_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['proctor_id'], ['proctors.id'], )
    )
    op.create_table('prof_assignment',
    sa.Column('prof_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['prof_id'], ['professors.id'], )
    )
    op.create_table('resident_assignment',
    sa.Column('resident_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resident_assignment')
    op.drop_table('prof_assignment')
    op.drop_table('proctor_assignment')
    op.drop_table('absences')
    op.drop_table('room_proctor')
    op.drop_index(op.f('ix_residents_name'), table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_professors_name'), table_name='professors')
    op.drop_table('professors')
    op.drop_index(op.f('ix_history_records_user_id'), table_name='history_records')
    op.drop_index(op.f('ix_history_records_period_name'), table_name='history_records')
    op.drop_index(op.f('ix_history_records_id'), table_name='history_records')
    op.drop_table('history_records')
    op.drop_table('exam_room')
    op.drop_index(op.f('ix_config_change_logs_user_id'), table_name='config_change_logs')
    op.drop_index(op.f('ix_config_change_logs_timestamp'), table_name='config_change_logs')
    op.drop_index(op.f('ix_config_change_logs_id'), table_name='config_change_logs')
    op.drop_index(op.f('ix_config_change_logs_entity_type'), table_name='config_change_logs')
    op.drop_index(op.f('ix_config_change_logs_entity_id'), table_name='config_change_logs')
    op.drop_index(op.f('ix_config_change_logs_action'), table_name='config_change_logs')
    op.drop_table('config_change_logs')
    op.drop_index(op.f('ix_assignments_room_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_exam_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('proctors')
    op.drop_index(op.f('ix_exams_promo'), table_name='exams')
    op.drop_index(op.f('ix_exams_date'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
